# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.7


workflows:
    heroku-deploy:
      jobs:
        - node/test
        - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          requires:
            - node/test
